name: CommandReq
main: me.akamuru.commandreq.CommandReq
version: 1.1
api-version: 1.17
commands:
   http-get:
      description: Sends an HTTP GET request. Default timeout is 250ms.
      usage: /http-get <server url> [param1] [param2..]
      permission: commandreq.http-get
   pussie:
      description: kitteh?
      usage: /pussie
      permission: commandreq.pussie
permissions:
   commandreq.pussie:
      default: true
   commandreq.http-get:
      default: op